# A workflow to update the README adding links to each .md file

name: Update README with new links
on:
  push:
    paths:
      - '**.md'

jobs:
  findmdfiles:
    runs-on: ubuntu-latest
    outputs:
      md_files: ${{ steps.files.outputs.md_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get all md files
        id: files
        run: |
          files=$(find . -type f -name "*.md" ! -name "md_links.md" ! -path "README.md")
          echo "Found files: $files"
          echo "::set-output name=md_files::$files"
  
  add-links:  
    runs-on: ubuntu-latest
    needs: findmdfiles
    if: ${{needs.files.outputs.md_files}}
    steps: 
      - name: Clear md_links.md
        run: |
          echo "" > md_links.md
          
      - name: List changed files & create links
        run: |
          for file in ${{needs.files.outputs.md_files }}; do
            file_path="${file#./}
            header=$(head -n 1 "$file")
              if [[ "$header" =~ ^#\ (.+) ]]; then
                name="${BASH_REMATCH[1]}"
              else
                name=$(basename "$file")
              fi
            echo "- [${name}](${file_path})" >> md_links.md
          done
          
      - name: Update README
        run: |
          sed -i '/<!-- MD LINKS START -->/,/<!-- MD LINKS END -->/ {  /<!-- MD LINKS START -->/!{/<!-- MD LINKS END -->/!d} }' README.md && sed -i '/<!-- MD LINKS START -->/r md_links.md' README.md
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add README.md && git add md_links.md && git commit -m "Update README with new files links" && git push)

