# This is a basic workflow to help you get started with Actions

name: Update README with new links
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate MD Links
        run: |
          index=0
          find . -name "*.md" ! -path "./README.md" ! -path "./md_links.md" -printf '%T@ %p\n' | sort -n | while read -r timestamp file; do
            file_path="${file#./}"
            header=$(grep -m 1 '^# ' "$file")
            if [[ -n "$header" ]]; then
              name=$(echo "$header" | sed 's/^#*\s*//')  # Remove the `#` symbol and any spaces
            else
              name=$(basename "$file")  # Use the file name if no header
            fi
            index=$((index + 1))
            echo "${index}. [${name}](${file_path})" >> md_links.md
          done
          
      - name: Update README
        run: |
          awk '/<!-- MD LINKS START -->/{print; system("cat md_links.md"); next} /<!-- MD LINKS END -->/{found=1} !found' README.md > temp.md
          mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add README.md && git commit -m "Update README with new files links" && git push)


