# A workflow to update the README adding links to each .md file

name: Update README with new links
on:
  push:
    paths:
      - '**.md'

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      md: ${{ steps.changes.outputs.md }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=md::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .md$ --exclude=md_links.md --exclude=README.md | xargs)"  
 
  add-new-links:  
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.md}}
    steps: 
      - name: List changed files & create links
        run: |
          for file in ${{needs.changedfiles.outputs.md}}; do
            file_path="${file#./}
            header=$(head -n 1 "$file")
              if [[ "$header" =~ ^#\ (.+) ]]; then
                name="${BASH_REMATCH[1]}"
              else
                name=$(basename "$file")
              fi
            echo "- [${name}](${file_path})" >> md_links.md
          done
          
      - name: Update README
        run: |
          sed -i '/<!-- MD LINKS START -->/,/<!-- MD LINKS END -->/ {  /<!-- MD LINKS START -->/!{/<!-- MD LINKS END -->/!d} }' README.md && sed -i '/<!-- MD LINKS START -->/r md_links.md' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add README.md && git add md_links.md && git commit -m "Update README with new files links" && git push)

