# A workflow to update the README adding links to each .md file

name: Update README with new links
on:
  push:
    paths:
      - '**.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          
      - name: List changed files & create links
        run: |
          index=$((index + 1))
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            header=$(head -n 1 "$file")
              if [[ "$header" =~ ^#\ (.+) ]]; then
                name="${BASH_REMATCH[1]}"
              else
                name=$(basename "$file")
              fi
            echo "${index}. [${name}](${file_path})" >> md_links.md
          done
          
      - name: Update README
        run: |
          awk '/<!-- MD LINKS START -->/{print; system("cat md_links.md"); next} /<!-- MD LINKS END -->/{found=1} !found' README.md > temp.md
          echo "<!-- MD LINKS END -->" >> temp.md
          mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add README.md && git add md_links.md && git commit -m "Update README with new files links" && git push)

