# A workflow to update the README adding links to each .md file

name: Update README with new links
on:
  push:
    paths:
      - '**.md'

jobs:
  addREADMElinks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find md files
        id: find-files
        run: |
          files=$(find . -type f -name "*.md" ! -name "md_links.md" ! -path "README.md")
          echo "md_files=$files" >> "$GITHUB_OUTPUT"
      - name: Get md files & create links
        env:
          MD_FILES: ${{ steps.find-files.outputs.md_files }}
        run: |
          echo "" > md_links.md
          for file in $MD_FILES; do
            file_path="${file#./}
            header=$(head -n 1 "$file")
              if [[ "$header" =~ ^#\ (.+) ]]; then
                name="${BASH_REMATCH[1]}"
              else
                name=$(basename "$file")
              fi
            echo "- [${name}](${file_path})" >> md_links.md
          done
          
      - name: Update README
        run: |
          sed -i '/<!-- MD LINKS START -->/,/<!-- MD LINKS END -->/ {  /<!-- MD LINKS START -->/!{/<!-- MD LINKS END -->/!d} }' README.md && sed -i '/<!-- MD LINKS START -->/r md_links.md' README.md
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add README.md && git add md_links.md && git commit -m "Update README with new files links" && git push)

