# This is a basic workflow to update the README adding links to each .md file

name: Update README with new links
on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate MD Links
        run: |

          find . -name "*.md" ! -path "./README.md" ! -path "./md_links.md" -printf '%T@ %p\n' | sort -n | while read -r timestamp file; do file_path="${file#./}"

          
          header=$(head -n 1 "$file")
          if [[ "$header" =~ ^#\ (.+) ]]; then
            name="${BASH_REMATCH[1]}"
          else
            name=$(basename "$file")
          fi
          index=$((index + 1))
          echo "${index}. [${name}](${file_path})" >> md_links.md
            
          done
          
      - name: Update README
        run: |
          awk '/<!-- MD LINKS START -->/{print; system("cat md_links.md"); next} /<!-- MD LINKS END -->/{found=1} !found' README.md > temp.md
          echo "<!-- MD LINKS END -->" >> temp.md
          mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add README.md && git commit -m "Update README with new files links" && git push)

